release: cd ../frontend && npm install && npm run build && cd ../backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: gunicorn bluewardrobe.wsgi:application --bind 0.0.0.0:$PORT

