# Generated by Django 6.0.2 on 2026-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_remove_design_images_remove_design_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='video',
            field=models.FileField(blank=True, help_text='Product video file (MP4, WebM, etc.)', null=True, storage='video_storage', upload_to='designs/videos/'),
        ),
    ]
