# Generated by Django 6.0.2 on 2026-03-10 22:42

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_design_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='video',
            field=models.FileField(blank=True, help_text='Product video file (MP4, WebM, etc.)', null=True, storage=store.models.get_video_storage, upload_to='designs/videos/'),
        ),
    ]
