# Generated by Django 6.0.2 on 2026-03-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_design_video'),
    ]

    operations = [
    ]
