# Generated by Django 6.0.2 on 2026-03-15 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20260316_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')])),
                ('bust', models.DecimalField(decimal_places=1, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hips', models.DecimalField(decimal_places=1, max_digits=5)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_measurements', to='store.design')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('design', 'size')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizemeasurement'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'design', 'size_measurement')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
