# Generated by Django 6.0.2 on 2026-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_video_likes_video_video_file_video_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4, WebM, etc.)', null=True, storage='video_storage', upload_to='videos/'),
        ),
    ]
