# Generated by Django 6.0.2 on 2026-03-18 17:00

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4, WebM, etc.)', null=True, storage=store.models.Video.get_video_storage, upload_to='videos/'),
        ),
    ]
