# Generated by Django 6.0.2 on 2026-03-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='store.videocomment')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('comment', 'ip_address')},
            },
        ),
    ]
