# Generated by Django 6.0.2 on 2026-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_videocommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocommentlike',
            name='session_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='session_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
