# Generated by Django 6.0.2 on 2026-03-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_videocommentlike_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the review is approved and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.design')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('design', 'email')},
            },
        ),
    ]
