# Generated by Django 6.0.2 on 2026-03-19 18:37

from django.db import migrations


def fix_video_field_data(apps, schema_editor):
    """
    Fix video field data by converting string values to None
    This resolves the AttributeError when trying to save designs in admin
    """
    Design = apps.get_model('store', 'Design')
    
    # Find all designs with video field that contains string data
    designs_with_string_video = Design.objects.exclude(video__isnull=True).exclude(video='')
    
    count = 0
    for design in designs_with_string_video:
        # Check if video field contains a string (not a proper FileField)
        if design.video and isinstance(design.video, str):
            print(f"Fixing video field for design {design.id}: {design.title}")
            # Set video to None to avoid FileField errors
            design.video = None
            design.save(update_fields=['video'])
            count += 1
        elif design.video and hasattr(design.video, 'name'):
            # Check if it's a proper FileField but with invalid path
            try:
                # Try to access file properties to see if it's valid
                _ = design.video.name
                _ = design.video.size
            except (AttributeError, ValueError, OSError):
                print(f"Clearing invalid video file for design {design.id}: {design.title}")
                design.video = None
                design.save(update_fields=['video'])
                count += 1
    
    print(f"Fixed video field for {count} designs")


def reverse_fix_video_field_data(apps, schema_editor):
    """
    No reverse operation needed - this is a data cleanup migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_designreview'),
    ]

    operations = [
        migrations.RunPython(fix_video_field_data, reverse_fix_video_field_data),
    ]
