# Generated by Django 6.0.2 on 2026-03-19 20:21

from django.db import migrations, models


def clean_remaining_video_data(apps, schema_editor):
    """
    Clean any remaining invalid video data that might cause issues
    """
    Design = apps.get_model('store', 'Design')
    
    # Find designs with video data that might be problematic
    designs = Design.objects.all()
    
    count = 0
    for design in designs:
        if design.video:
            try:
                # Try to access video properties to validate
                video_name = design.video.name if hasattr(design.video, 'name') else str(design.video)
                
                # Check if it looks like invalid string data
                if isinstance(video_name, str) and ('invalid' in video_name.lower() or not video_name.endswith(('.mp4', '.webm', '.mov', '.avi'))):
                    print(f"Cleaning invalid video data for design {design.id}: {design.sku}")
                    # Direct database update to bypass model methods
                    Design.objects.filter(pk=design.pk).update(video=None)
                    count += 1
                elif hasattr(design.video, 'size'):
                    # Try to access size to validate file
                    _ = design.video.size
                    
            except (AttributeError, ValueError, OSError) as e:
                print(f"Cleaning problematic video data for design {design.id}: {design.sku} - {e}")
                Design.objects.filter(pk=design.pk).update(video=None)
                count += 1
    
    print(f"Cleaned video data for {count} designs")


def reverse_clean_remaining_video_data(apps, schema_editor):
    """
    No reverse operation needed - this is a data cleanup migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_fix_video_field_data'),
    ]

    operations = [
        migrations.RunPython(clean_remaining_video_data, reverse_clean_remaining_video_data),
    ]
