# Generated by Django 6.0.2 on 2026-03-23 21:16

import store.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_clean_remaining_video_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='video',
            field=store.models.SafeVideoField(blank=True, help_text='Product video file (MP4, WebM, etc.)', null=True, storage='video_storage', upload_to='designs/videos/'),
        ),
    ]
