# Generated by Django 6.0.2 on 2026-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_use_safe_video_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='video',
            field=models.FileField(blank=True, help_text='Product video file (MP4, WebM, etc.)', null=True, storage='video_storage', upload_to='designs/videos/'),
        ),
    ]
