# Generated by Django 6.0.2 on 2026-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_fix_video_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='video',
            field=models.FileField(blank=True, help_text='Product video file (MP4, WebM, etc.)', null=True, upload_to='designs/videos/'),
        ),
    ]
