# Generated by Django 6.0.2 on 2026-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_fix_design_video_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flutterwave_tx_ref',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='', help_text='Gateway used for this order (set automatically on payment)', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='gateway',
            field=models.CharField(blank=True, help_text='paystack or flutterwave', max_length=20),
        ),
    ]
