# Generated by Django migration (manual)

from decimal import Decimal

from django.db import migrations, models
from django.db.models import F


def seed_fx_and_backfill_orders(apps, schema_editor):
    StoreCurrencySettings = apps.get_model("store", "StoreCurrencySettings")
    Order = apps.get_model("store", "Order")
    StoreCurrencySettings.objects.get_or_create(
        pk=1,
        defaults={
            "ngn_per_usd": Decimal("1550"),
            "ngn_per_gbp": Decimal("1980"),
        },
    )
    Order.objects.all().update(total_ngn_equivalent=F("total_amount"))


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_order_delivery_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreCurrencySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ngn_per_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1550"),
                        help_text="NGN per 1 USD (e.g. 1550 means $1 ≈ ₦1,550)",
                        max_digits=14,
                    ),
                ),
                (
                    "ngn_per_gbp",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1980"),
                        help_text="NGN per 1 GBP (e.g. 1980 means £1 ≈ ₦1,980)",
                        max_digits=14,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store currency & FX",
                "verbose_name_plural": "Store currency & FX",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="NGN",
                help_text="ISO 4217 currency the customer was charged in",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_ngn_equivalent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Same order total expressed in NGN for unified sales reporting",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="currency",
            field=models.CharField(default="NGN", max_length=3),
        ),
        migrations.RunPython(seed_fx_and_backfill_orders, migrations.RunPython.noop),
    ]
