# Generated by Django 6.0.2 on 2026-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_design_newest_first_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee in NGN at purchase time (from store settings)', max_digits=12),
        ),
    ]
